### ISSUE TITLE
FileNotFoundError: [Errno 2] File b'./DI-tector_output_sorted.txt' does not exist: b'./DI-tector_output_sorted.txt'

### ISSUE THREAD

**Issue by mbartl13** [adigioacchino/sgDI-tector#1]
I am trying to use DI-tector but am getting an error with the output file- any suggestions for how to fix?

`python3 sgDI-tector.py -f --DVG_sequences /dcl02/leased/giffin/SINV_nanopore/SINV.fasta /dcl02/leased/giffin/SINV_nanopore/combined_DNA.fasta 
`

[M::mem_process_seqs] Processed 5348 reads in 34.432 CPU sec, 34.325 real sec
[M::process] read 1864 sequences (3114546 bp)...
[M::mem_process_seqs] Processed 5616 reads in 33.444 CPU sec, 33.357 real sec
[M::mem_process_seqs] Processed 1864 reads in 10.554 CPU sec, 10.481 real sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -t 1 /dcl02/leased/giffin/SINV_nanopore/ViReMa/SINV.fasta /dcl02/leased/giffin/
[main] Real time: 6183.812 sec; CPU: 6199.118 sec
[bam_sort_core] merging from 4 files and 1 in-memory blocks...
=================================
Step 1/5 : Done! 1,436,118 reads left after filtering (150.77%) (110m 24s)
=================================

=================================
Step 2/5 : Segmentation...
=================================
Segmentation: [===                 ] 15.3% Elapsed: 47m 04s ETA: 260m32s Traceback (most recent call last):
  File "DI-tector_06.py", line 226, in <module>
    file_segment.write("@SEGL"+str(no_seg).zfill(3)+":"+str(len_SEQ).zfill(3)+"::"+QNAME+"\n"+SEQ[no_seg:]+"\n")
OSError: [Errno 27] File too large

During handling of the above exception, another exception occurred:

OSError: [Errno 27] File too large

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DI-tector_06.py", line 236, in <module>
    draw_progress_bar("Segmentation: ", no_line/nb_reads_after_filtering, timer_start)
OSError: [Errno 27] File too large
Done!
Loading DVG data... Traceback (most recent call last):
  File "sgDI-tector.py", line 305, in <module>
    t_df = pd.read_csv(ditect_outfile_outsor, sep='\t')
  File "/users/mbartlet/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/users/mbartlet/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/users/mbartlet/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/users/mbartlet/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/users/mbartlet/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./DI-tector_output_sorted.txt' does not exist: b'./DI-tector_output_sorted.txt'
[mbartlet@compute-105 sgDI-tector]$ ls
DI-tector_06.py                         DI-tector_temp_file_woVirus.sam  __MACOSX
DI-tector_temp_file_onVirus.sam         DI-tector_temp_seqment.fq        README.md
DI-tector_temp_file_Virus.bam           input_examples                   sgDI-tector.py
DI-tector_temp_file_Virus_Coverage.txt  LICENSE.txt
[

**Comment by adigioacchino** [comment]
Hi @mbartl13,

it seems that the error you see originates during the DI-tector execution. Actually sgDI-tector was not monitoring the exit state of the DI-tector call, now I changed the code and this is checked. Could you please run everything again and confirm that you get an error message such as "AssertionError: ERROR: DI-tector call failed, exiting..."? This would mean that the problem is indeed in the first passage of the sgDI-tector pipeline, that is in running DI-tector. 
I also added an example fastq file and instructions on the README about how to do a test of sgDI-tector, you can try and see if that works.

Finally, you get an "OSError: [Errno 27] File too large" error. It happens during the "Segmentation" step of DI-tector, where a (potentially very) large file is created. Depending on your file system, the maximum allowed file size can be [very small](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). 

Finally, are you using nanopore sequencing data? If reads are long and many DVG reads are present this can cause the file created during the "Segmentation" step to be very large. You can reduce the size of this file by using the option `-s MIN_SEGMENT` with MIN_SEGMENT larger than 15 (the default value). Notice that in this case, however, you will prevent the software to recognize DVG reads with junctions which are closer to the 3' or 5' end of the read more than MIN_SEGMENT, so you can potentially miss important DVGs, depending on your data.
In any case, please take into account that DI-tector and sgDI-tector are designed to work with short-reads sequencing data.

**Comment by mbartl13** [comment]
Thanks so much- switched to use on Illumina data I have and working well now.
