### ISSUE TITLE
Filtering error

### ISSUE THREAD

**Issue by denise0593** [adigioacchino/sgDI-tector#2]
Hi! 
I'm trying sgDI on my sample using the following command line:

`python3 sgDI-tector.py -r SARS-CoV-2.fasta trimmed.R1.fastq.gz trimmed.R2.fastq.gz`

and I'm getting the following error:

```
=================================
Step 4/5 : Filtering...Analyses...
=================================
Traceback (most recent call last):
  File "/opt/sgDI-tector/DI-tector_06.py", line 280, in <module>
    for line in fasta_viral_file:
  File "/home/delavezz/anaconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/opt/sgDI-tector/sgDI-tector.py", line 298, in <module>
    assert dit_proc_out.returncode == 0, "ERROR: DI-tector call failed, exiting..."  
AssertionError: ERROR: DI-tector call failed, exiting...
```

any ideas why?

**Comment by adigioacchino** [comment]
Hi,

I think there could be a problem in the way input files are passed to sgDI-tector. Firstly, [DI-tector](https://rnajournal.cshlp.org/content/24/10/1285.long), the tool that sgDI uses to find valid defective interfering reads, cannot deal with paired-end reads, so I am afraid you will need to drop one of the two ends of your reads. Secondly, you need to provide the reference viral genome (SARS-CoV-2 in your case) as the first positional argument in the sgDI-tector call.
The `-r` option that you are using is optional and useful to give reference subgenomic RNAs that the tool uses to assign a name to the subgenomic RNAs observed in your sequencing data, see the [example file in the repo](https://github.com/adigioacchino/sgDI-tector/blob/master/input_examples/NC_045512.2_sgRNA.fasta).
What is happening in your case is that sgDI-tector is interpreting `trimmed.R1.fastq.gz` as the file containing the viral genome, and since it has to be a fasta file (uncompressed), I guess something goes wrong during the DI-tector call and it throws the `UnicodeDecodeError` error.

If I am right and this is the issue, you should change your command into something like (using R1 ends for instance):

`python3 sgDI-tector.py SARS-CoV-2.fasta trimmed.R1.fastq.gz`

or, if you want sgDI-tector to annotate for you some of the subgenomic region found:

`python3 sgDI-tector.py -r NC_045512.2_sgRNA.fasta SARS-CoV-2.fasta trimmed.R1.fastq.gz`

where `NC_045512.2_sgRNA.fasta` is taken from [here](https://github.com/adigioacchino/sgDI-tector/blob/master/input_examples/NC_045512.2_sgRNA.fasta) and it has to be in the same folder as `SARS-CoV-2.fasta` and `trimmed.R1.fastq.gz`.

Let me know if it works!

**Comment by denise0593** [comment]
Hi!
It works! Thanks a lot!
